# Generated by Django 4.0.2 on 2022-05-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('airline', models.CharField(blank=True, max_length=10, null=True)),
                ('credit_card', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_carrier', models.CharField(blank=True, max_length=10, null=True)),
                ('pay_application', models.CharField(blank=True, max_length=10, null=True)),
                ('min_cost', models.IntegerField(blank=True, null=True)),
                ('is_weekend', models.IntegerField(blank=True, null=True)),
                ('is_oneway', models.IntegerField(blank=True, null=True)),
                ('is_event', models.IntegerField(blank=True, null=True)),
                ('discount_type', models.CharField(blank=True, max_length=10, null=True)),
                ('duplicate', models.IntegerField(blank=True, null=True)),
                ('option', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'airline_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=2, null=True)),
                ('mobile_carrier', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_card', models.CharField(blank=True, max_length=100, null=True)),
                ('mc_grade', models.CharField(blank=True, max_length=11, null=True)),
                ('pay_application', models.CharField(blank=True, max_length=100, null=True)),
                ('new_card_will', models.IntegerField(blank=True, null=True)),
                ('new_mc_will', models.IntegerField(blank=True, null=True)),
                ('new_app_will', models.IntegerField(blank=True, null=True)),
                ('event_will', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
    ]
